language: node_js
node_js:
  - node
  - lts/*
  - 14
  - 12
  - 10
install:
  - npm ci
  - npm run bootstrap
script:
  - npm run lint
  - npm test
jobs:
  include:
    - stage: coverage
      node_js: node
      script:
        - jest --coverage
        - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
        - rm -rf ./coverage
